[package]
name = "bigweb_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
color-eyre = "0.6.2"
csv = "1.2.1"
derive_builder = "0.12.0"
dotenvy = "0.15.6"
futures = "0.3.27"
headless_chrome = { version = "1.0.5", default-features = false }
pest = "2.5.6"
pest_derive = "2.5.6"
scraper = "0.15.0"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
serde_qs = "0.12.0"
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "postgres", "offline", "uuid", "time", "bigdecimal"] }
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.40"
time = { version = "0.3.20", features = ["formatting"] }
tokio = { version = "1.26.0", features = ["full"] }
url = "2.3.1"
html-escape = "0.2.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
fantoccini = "0.19.3"
regex = "1.8.1"
lazy_static = "1.4.0"
reqwest = "0.11.17"
uuid = { version = "1.4.1", features = ["v4"] }
